---
# tasks file for apache2
- name: Install apache and python
  ansible.builtin.package:
    name:
      - apache 2
      - python
    state: latest

- name: Write the apache config file
  ansible.builtin.copy:
    src: "{{ ap2 }}"
    dest: /etc/apache2/apache2.conf

- name: Give Ownership Permissions
  ansible.builtin.file:
    path: /etc/apache2/apache2.conf
    owner: root
    group: root
    mode: '0644'

- name: Write the apache site file
  ansible.builtin.copy:
    src: "{{ indx }}"
    dest: /var/www/html/index.html

- name: Give Ownership Permissions
  ansible.builtin.file:
    path: /var/www/html/index.html
    owner:  root
    group: root
    mode: '0644'

- name: Create a symbolic link
  ansible.builtin.file:
    src: /etc/apache2/mods-available/headers.load
    dest: /etc/apache2/mods-enabled/headers.load
    state: link
  notify:
    - Restart apache2
