---
- hosts: db
  become: yes
  vars:
    mysql_import_data: "yes"
  roles:
    - update_apt
    - mysql
- hosts: webservers
  become: yes
  vars:
    mysql_import_data: "yes"
  roles:
    - update_apt
    - apache2
